### ISSUE TITLE
Library don't load IFC model

### ISSUE THREAD

**Issue by ngorlani** [tomvandig/web-ifc#100]
Hi,
I have try to load this IFC model:
[S01-NSP-ESE-A-ST-TE-ZAN-M3-000-000-00.zip](https://github.com/tomvandig/web-ifc/files/7462738/S01-NSP-ESE-A-ST-TE-ZAN-M3-000-000-00.zip)

In console (https://tomvandig.github.io/web-ifc/examples/viewer/index.html) I can see a lot of "no bueno" comments :D 
![image](https://user-images.githubusercontent.com/91492685/139913095-5d9e7e92-d270-4764-8575-3c92bc3767dc.png)

Can you help us?
Thanks

**Comment by agviegas** [comment]
After some time, last version of web-ifc loads it 😊

![image](https://user-images.githubusercontent.com/56475338/173795092-8eb93540-27a6-4ede-a5da-591077d4d939.png)
