### ISSUE TITLE
Model loading forever

### ISSUE THREAD

**Issue by agviegas** [tomvandig/web-ifc#103]
A model keeps loading forever and never finishes. A similar model with similar size from the same guys loads super fast. Both can be found [here](https://drive.google.com/drive/folders/1JgZSWz20_xQ-2UgHH5PUvMhvy9VlXRxz?usp=sharing).

Model that can be loaded: 

![image](https://user-images.githubusercontent.com/56475338/140627921-7de9295d-4385-420a-b1a7-51a32ee7c514.png)

Model that can't be loaded:

![image](https://user-images.githubusercontent.com/56475338/140627939-6ce25747-1c56-4ba8-9024-6c228e246e17.png)

**Comment by favreau84** [comment]
Hi @agviegas & @tomvandig , 
I recently upgraded the lib to the new versions : 

 "web-ifc":"^0.0.24"=>  "^0.0.28",
  "web-ifc-three": "^0.0.68" => "^0.0.80",

Now, I have some models that are not loaded, (but they did load before),  like this one [station_0.ifc.zip](https://github.com/tomvandig/web-ifc/files/7493293/station_0.ifc.zip)

Any idea ?
Thanks !

**Comment by agviegas** [comment]
More info: `USE_FAST_BOOLS=true` allows to load up to a point, but then it stops and throws that error 🤔 Maybe out of memory?
![image](https://user-images.githubusercontent.com/56475338/140753464-126fc91b-868e-421c-972b-9ba0f655a777.png)

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $100. More information [here](https://bounties.ifcjs.io/).

**Comment by agviegas** [comment]
Solved!
![image](https://user-images.githubusercontent.com/56475338/173802291-01ed2f74-1aef-4dd6-aa3a-64e244de3e0e.png)
