### ISSUE TITLE
Not properly or not converted at all some walls

### ISSUE THREAD

**Issue by TymofiiS** [tomvandig/web-ifc#108]
https://drive.google.com/file/d/1yzEtuOWBpqZ5mvdMp4SuFVFvAMvAgugZ/view?usp=sharing
https://drive.google.com/file/d/1h242zQ5_vcrvPggFGLtsF_QZrKm-EJ6o/view?usp=sharing

https://drive.google.com/file/d/10b2sDWHwXyjiKHrD0gVOxV3JqQorbqJW/view?usp=sharing
https://drive.google.com/file/d/1PZ8VHb6T49rLn_aIVOfB0BpOoJGVWlA4/view?usp=sharing

**Comment by tomvandig** [comment]
![image](https://user-images.githubusercontent.com/49716596/144502005-821d4fa7-0afd-4ccf-9005-44bd6cbec696.png)
![image](https://user-images.githubusercontent.com/49716596/144502063-f2d23260-2bdb-44a6-b833-3a4743e5b071.png)
Both these files will be fixed in the next release

**Comment by tomvandig** [comment]
Fixed in 0.0.30, please reopen if more issues arise.
