### ISSUE TITLE
Loading this model segfaults the browser.

### ISSUE THREAD

**Issue by haroldiedema** [tomvandig/web-ifc#11]
Uploading this model (http://iedema.me/crash.ifc) in the example viewer that is linked in the readme crashes the browser. I thought this might be helpful debugging IFC-support.

![image](https://user-images.githubusercontent.com/567518/110788993-a4098480-826f-11eb-9a07-0387fb63b7ef.png)

**Comment by tomvandig** [comment]
Thanks for reporting this, interesting that it crashes the tab!

I've fixed the particular crash, and supported some extra unsupported elements in the file. You can try it out here:

https://tomvandig.github.io/web-ifc/examples/viewer/index.html

**Comment by haroldiedema** [comment]
Nice! That was quick :smile: 

Tested & verified. Works as intended now!
