### ISSUE TITLE
Large model load warnings and error

### ISSUE THREAD

**Issue by cesarecaoduro** [tomvandig/web-ifc#113]
Shared the model for testing in private message on discord.
Takes about 30 minutes to load and, at the end of the process, the model doesn't show up. 
Would be interesting to have more detailed logs of the parsing process (they all come in one line...) with more information about the element class and the reason for failing.

**Comment by agviegas** [comment]
Hi @cesarecaoduro, could you please send us the model again? We now have resources and are trying to resolve all the issues of this repository. I think this is due to boolean operations, hopefully this will be solved next week. Cheers!

**Comment by agviegas** [comment]
If you are willing to share the model, feel free to open this again!
