### ISSUE TITLE
Absolute object placement

### ISSUE THREAD

**Issue by josesoutoleon** [tomvandig/web-ifc#116]
Actually is possible to get object placement coordinates wich are relative to another object, parent object.
Some times is very useful to know what is the absolute object placment referred to project placement coordinates.

So please add an absolute object placement property to objects in order to get it.

A more generic implementation woul be to get absolute placement not only referred to project placement, also get the absolute placement related to another object.

For me getting object absolute placment refered to project placment is good enough.

Thank you.

**Comment by agviegas** [comment]
Hi, I think we already talked about his and I resolved this issue for your use case, so I'm closing this!
