### ISSUE TITLE
Testing a 200MB model • several warnings in the console

### ISSUE THREAD

**Issue by favreau84** [tomvandig/web-ifc#119]
@tomvandig , here is a 200MB that takes several minutes to load.  A lot of warnings are displayed while loading. It is a good file example to test a loading indicator (#104 ).

The model can be dowloaded from this[ Google drive location](https://drive.google.com/file/d/1ufKEZblNkBIfd5_u-Jht4fb6bG5ipuw6/view?usp=sharing)

<img width="1507" alt="stop at 30680" src="https://user-images.githubusercontent.com/18169247/146071091-d86455bc-e632-408a-8f88-eb3a29159291.png">

<img width="790" alt="Screenshot 2021-12-14 at 20 40 20" src="https://user-images.githubusercontent.com/18169247/146070914-1d9a27c3-37ca-477b-a659-9e656fa65955.png">

**Comment by favreau84** [comment]
Hi ! any news on this issue ? I updated web-ifc-three to 0.0.102 / web-ifc 0.0.32 but still this very long loading process. Thanks in advance !!

**Comment by tomvandig** [comment]
![image](https://user-images.githubusercontent.com/49716596/151717064-3ec1b4ae-7112-4609-be1f-4ef46599f1eb.png)
Took a long time, but I rewrote the bool logic and this file now loads in 35 secs, can probably do much better than that in the future. I will update this when its released, hopefully soon.

**Comment by favreau84** [comment]
@tomvandig , this news is the sunshine of my day !!! 35secs, that's just awsome !! Is there a way to track the progress of these 35secs or is it still in the "loading part" to be implemented ?

**Comment by favreau84** [comment]
@tomvandig , @agviegas , is this enhancement going to be released soon ? I was so enthusiastic to hear that the model could be loaded in less than 35sec !!

**Comment by agviegas** [comment]
Hi @favreau84 the main reason not to publish the version yet is the [material regression in version 34](https://github.com/tomvandig/web-ifc/issues/143). We might undo those changes and then publish. I'll try to make some time this weekend.

**Comment by agviegas** [comment]
We will release the new version next week. As this is already resolved, I'm closing this. Also, keep in mind the new glTF approach, which would allow you to load that kind of model in less than 10 seconds. 🙂

**Comment by agviegas** [comment]
Sorry for the delay @favreau84, we just published 0.0.35. There are tons of things solved 🙂 Bounties are speeding everything up.

**Comment by favreau84** [comment]
Great! Thanks a lot @agviegas !!
