### ISSUE TITLE
Execution time is too slow.

### ISSUE THREAD

**Issue by sulhamri** [tomvandig/web-ifc#128]
Hi! am doing queries to the property sets of all the elements (wall, slab, covering, ..) that are in each buildingstorey of the building,  to obtain parameters like area, thermal transmission, volume,.. but the execution time to do this part is too long (3 minutes). To obtain the property sets I put the parameter recursive = false and once I look for the property set that I want, I obtain all its parameters with the "getItemProperties" function. Is there a more efficient way to do these queries? Thank you.

**Comment by agviegas** [comment]
Querying hundreds of properties is indeed slow. Have you tried fetching the properties lazily (as your user requests them)? Another option is to create a JSON file from that IFC file that you could then use to make such big query. You can check out an example of how to do that [here](https://github.com/IFCjs/hello-world/tree/main/examples/web-ifc/ifc-to-json).

**Comment by agviegas** [comment]
I'm closing this for now. Exporting to JSON should solve this issue. If you need more speed, you need to use a database, as querying raw data with databases can't be as efficient as a proper database (that's why the exist). If you have any other question regarding this, let us know!
