### ISSUE TITLE
[3D rendering issue] In the attached model, slabs are not rendered correctly

### ISSUE THREAD

**Issue by favreau84** [tomvandig/web-ifc#129]
# Model
[PN1540_17_EXE_MOD_448200_02_09_11SMC_IGC_V17.ifc.zip](https://github.com/tomvandig/web-ifc/files/7880964/PN1540_17_EXE_MOD_448200_02_09_11SMC_IGC_V17.ifc.zip)

# OK vs KO

![Screenshot 2022-01-17 at 11 12 19](https://user-images.githubusercontent.com/18169247/149750519-95a3e129-cd39-432a-834f-0f734069109d.png)

**Comment by agviegas** [comment]
Solved! 
![image](https://user-images.githubusercontent.com/56475338/173802746-0d06465b-c447-41ef-b7e9-6523e1c48e45.png)
