### ISSUE TITLE
Support for IFCPOLYGONALFACESET

### ISSUE THREAD

**Issue by LaurensJN** [tomvandig/web-ifc#13]
Hi! I was checking out the wonderful new approach and tried to load some IFC files. Very fast indeed! 

I got one error in a file, turns out we use IFCPOLYGONALFACESET a lot here. I think they are not supported yet, I got the error _Unexpected mesh type: 2839578677 at line ..._ 

Do you think you will be able to support that soon? I could provide you with an IFC file if you want an example.

**Comment by tomvandig** [comment]
Hi Laurens,

Thanks for your interest in the project.

IFCPOLYGONALFACESET does not look particularly complicated, so I think it would be good idea indeed.
If you provide me with an example model, I will try to get back to you as soon as I can!

Cheers,
Tom

**Comment by LaurensJN** [comment]
Thanks Tom! I contacted you on discord to send you the file.

**Comment by tomvandig** [comment]
![image](https://user-images.githubusercontent.com/49716596/111495646-dfa8c080-873f-11eb-8b06-c323f923106a.png)

Example deploy should have a first go at IFCPOLYGONALFACESET, please let me know if it shows the expected results :)

**Comment by LaurensJN** [comment]
Thank you very much! This is perfect.
