### ISSUE TITLE
Chrome version

### ISSUE THREAD

**Issue by tomerel22** [tomvandig/web-ifc#130]
Is it possible to fix the problem that the web-ifc doesn't support Chrome V68?
Thanks!

**Comment by tomvandig** [comment]
What kind of issue are you facing?

**Comment by tomerel22** [comment]
I can't use web-ifc-api in chrome68, it throws me an error message.

**Comment by agviegas** [comment]
If you are not more specific, we won't be able to help you at all. We need steps to reproduce the error, the error logs, etc.

**Comment by tomerel22** [comment]
I'm trying to loading an ifc model in [Online3DViewer](https://github.com/kovacsv/Online3DViewer) that uses yours code to loading ifc model.
I'm using chrome 68 and when I tried to load a model the viewer is loading with no response, while I'm doing it in chrome 77 for example, the same model has been loaded. Do you have any idea how can I change maybe packages or something like that for using your code (the web-ifc-api) in chrome 68?

**Comment by tomerel22** [comment]
Uncaught (in promise) RunTimeError: memory access out of bounds
at wasm-function[843]:34
at wasm-functions[506]:1
at Modules.__wasm_calls_ctors

Do you recognize the error?

**Comment by tomvandig** [comment]
Hi, I'm sorry but I don't recognize this error. It seems that wasm is supported for chrome 68 though, so that can't be it. What is your use case? Are you using an embedded browser?

**Comment by agviegas** [comment]
As it looks like this error doesn't belong to this repository, I'm closing this.
