### ISSUE TITLE
Are the names for IfcRelFillsElement arrtibutes wrong?

### ISSUE THREAD

**Issue by sulhamri** [tomvandig/web-ifc#132]
In the documentation of IFC the attribute names of IfcRelFillsElement  are: RelatedOpeningElement and RelatingBuildingElement. However, in the objects I get with IFC.js the attribute names are: RelatingOpeningElement and RelatedBuildingElement. This could cause a confusion.

**Comment by tomvandig** [comment]
I'm not sure, but these docs: https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcproductextension/lexical/ifcrelfillselement.htm 
Use the same naming as ifc.js, isn't that correct?

**Comment by sulhamri** [comment]
Hi! The names of RelatedOpeningElement and RelatingBuildingElement aren't the same. In ifc.js are RelatingOpeningElement and RelatedBuildingElement.

**Comment by agviegas** [comment]
Hi, RelatingOpeningElement and RelatedBuildingElement is the way it's defined in the buildingSMART documentation. I'm closing this!

![image](https://user-images.githubusercontent.com/56475338/168485804-332b85ab-fc25-45b7-ae58-99d31e60c00a.png)
