### ISSUE TITLE
C API or .NET wrapper

### ISSUE THREAD

**Issue by arturred** [tomvandig/web-ifc#133]
Hi
I would like to use this library in other languages but cannot use C++ directly (Delphi, .NET). Is there a wrapper or C API header that exposes the minimum functionality to open IFC files and view them in 3D?

**Comment by tomvandig** [comment]
Hi, no there is not. Right now the major API is a bridge from cpp to js through Emscripten. The main API's in c++ are web-ifc.h and web-ifc-geometry.h, neither are C API's but it's possible to make one. If you are interested in doing this, that would be a great contribution, let me know and I can help you out.

**Comment by agviegas** [comment]
Hi, I'm closing this for now. If in the future there's enough interest from multiple people or you are willing to help us with this, feel free to open it again.
