### ISSUE TITLE
Incorrect Rendering Issue

### ISSUE THREAD

**Issue by simon-gd** [tomvandig/web-ifc#134]
Attaching a screenshots and IFC model of a example Solibri buildings that web-ifc seems to have trouble with.

![web-ifc-three](https://user-images.githubusercontent.com/57882634/147614593-6c94f96d-8571-4920-ad6c-5d74fc7c271d.png)

![Same model in BIM Vision](https://user-images.githubusercontent.com/57882634/147614596-902d637e-f195-471a-820b-b016e5f54883.png)

[Solibri.Building.zip](https://github.com/tomvandig/web-ifc/files/7909042/Solibri.Building.zip)

**Comment by tomvandig** [comment]
Hi, this looks like a problem where the curve sense is inverted, I've seen this before on some models. Thanks for reporting the issue, I'll take a look when I have time.

**Comment by agviegas** [comment]
Solved! Available from `0.0.36`.
![image](https://user-images.githubusercontent.com/56475338/173812979-37b0497f-b538-4719-a52b-b546e03336d7.png)
