### ISSUE TITLE
Strange behavior for materials rendering

### ISSUE THREAD

**Issue by thmax** [tomvandig/web-ifc#135]
Hey !
I'm having an issue with the materials when i use the ifcLoader from web-ifc-three.
On the first photo, you can see some materials'color is white (i also trie with the viewer and it looks the same).
If I load the same model on Trimble, the materials are fine (second photo).

![image](https://user-images.githubusercontent.com/52961165/150495084-8ea79779-056f-49ad-91f0-8a52d17d8d5b.png)
![image](https://user-images.githubusercontent.com/52961165/150495094-9116a85c-da64-4821-b7b6-7f254a0af925.png)
[Maquette.BETA-B.zip](https://github.com/tomvandig/web-ifc/files/7911673/Maquette.BETA-B.zip)

**Comment by thmax** [comment]
Any news on this ?

**Comment by tomvandig** [comment]
Fixed in 0.0.34
![Screenshot 2022-02-11 214052](https://user-images.githubusercontent.com/49716596/153667141-5dddd80f-6891-4a4f-9ded-a218586d83c5.png)
