### ISSUE TITLE
Node example incorrect

### ISSUE THREAD

**Issue by beachtom** [tomvandig/web-ifc#136]
Hi,

I attempted to implement some batch processing using node js. The example code has these lines in it:

const ifcData = fs.readFileSync(filename).toString();
await ifcapi.Init();
let modelID = ifcapi.OpenModel(ifcData);

but this produced errors as it seems OpenModels expects a typed array. So instead I had to change to:

const ifcData = fs.readFileSync(fileName);
await ifcapi.Init();
let modelID = await ifcapi.OpenModel(ifcData);

**Comment by tomvandig** [comment]
Sorry about this, and thanks for letting me know. Fixed it: https://github.com/tomvandig/web-ifc/blob/main/examples/nodejs/index.js
