### ISSUE TITLE
Modify & export one ifc file in the context of web-ifc-three.js

### ISSUE THREAD

**Issue by favreau84** [tomvandig/web-ifc#138]
# In a nutshell
**Problem 1** : the webworkers serialization drop typing => ifcManager.getLine() doesn't return the full object.
**Problem 2**: the export in 0.0.32 is garbled.

# Context

https://discord.com/channels/799990228336115742/799990228336115745/935220750955212860

![image](https://user-images.githubusercontent.com/18169247/151183074-ea5270e8-774d-4926-ab44-33c55a4ae9bb.png)

# Why it would be super useful ?

The typical use case would be to modify the ifcSite position/rotation of one model

<img width="899" alt="Screenshot 2022-01-26 at 15 30 44" src="https://user-images.githubusercontent.com/18169247/151181925-b5a4046c-a1ad-4b6a-8996-dd3174cc99a9.png">

**Comment by tomvandig** [comment]
@favreau84 The export has been fixed in WI 0.0.33, however the webworkers serialization is part of web ifc three, not this repo. Can you open a ticket there?

**Comment by favreau84** [comment]
Great, thanks @tomvandig ! just created the issue (cc @agviegas )
