### ISSUE TITLE
Create function getIfcType

### ISSUE THREAD

**Issue by sulhamri** [tomvandig/web-ifc#140]
In web-ifc-three there is a function called getIfcType and I'm looking for the same function (or similar) in web-ifc. @agviegas told me that he could implement it there. We are using web-ifc-api-node. Thank you.

IfcLoader.IfcManager.getIfcType (
                        modelID: number,
                        id: number,
                        ): string;

**Comment by agviegas** [comment]
Done! Will be available from the next version (`0.0.35`).
