### ISSUE TITLE
[3D rendering issue] In the attached model, bracing bars are not displayed correctly

### ISSUE THREAD

**Issue by favreau84** [tomvandig/web-ifc#141]
## Model

[20220202-Couverture Grande Trémie.ifc.zip](https://github.com/tomvandig/web-ifc/files/7988930/20220202-Couverture.Grande.Tremie.ifc.zip)

## OK vs KO

<img width="569" alt="Screenshot 2022-02-02 at 18 51 39" src="https://user-images.githubusercontent.com/18169247/152209709-84127f28-ccb2-4fa6-bd99-c195a50099a8.png">

## Other geometry pb
- https://github.com/tomvandig/web-ifc/issues/129
- https://github.com/tomvandig/web-ifc/issues/121
- https://github.com/tomvandig/web-ifc/issues/102

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $200. More information [here](https://bounties.ifcjs.io/).

**Comment by QuimMoya** [comment]
I think we have already solved this issue but i have to verify it
![image](https://user-images.githubusercontent.com/12625508/168553071-276acdab-4021-4310-a893-1c79305e96a7.png)

**Comment by agviegas** [comment]
Solved in `0.0.35`!
