### ISSUE TITLE
Wrong materials in 0.0.34

### ISSUE THREAD

**Issue by kovacsv** [tomvandig/web-ifc#143]
[Online3DViewer](https://github.com/kovacsv/Online3DViewer) regression tests failed after updating to web-ifc 0.0.34. The same error happens in the official demo as well.

Examples (0.0.33 vs. 0.0.34):

<img src="https://user-images.githubusercontent.com/2034315/153767547-f9fd6579-679a-4e2b-bedf-24dea4147b6e.png" width="400"><img src="https://user-images.githubusercontent.com/2034315/153767584-004f30e9-0e11-4635-ad97-323803beee7c.png" width="400">

<img src="https://user-images.githubusercontent.com/2034315/153767589-d7ef1b5e-347b-4412-be7d-0dd78f4904a9.png" width="400"><img src="https://user-images.githubusercontent.com/2034315/153767592-e5be0324-e177-4349-8600-8a222847870c.png" width="400">

**Comment by tomvandig** [comment]
Cool, thanks for the notice!

**Comment by kovacsv** [comment]
Here they are:
https://github.com/IFCjs/test-ifc-files/blob/main/Others/479l7.ifc
https://github.com/IFCjs/test-ifc-files/blob/main/Others/haus.ifc

**Comment by QuimMoya** [comment]
We made some fixes and now we get similar results with other viewers. We will publish changes after reviewing.

**Comment by agviegas** [comment]
Solved [here](https://github.com/tomvandig/web-ifc/pull/160).
