### ISSUE TITLE
displaying my ifc 4

### ISSUE THREAD

**Issue by tomerel22** [tomvandig/web-ifc#144]
hi! I can't display the walls of my model. 
![Screenshot from 2022-02-15 15-31-06](https://user-images.githubusercontent.com/80748720/154073213-27a672d1-3a54-4500-b7e0-44d3dde0f890.png)
I attached my file with .txt at the end but you can remove the txt to display the model
[building1.ifc.txt](https://github.com/tomvandig/web-ifc/files/8069533/building1.ifc.txt)

**Comment by QuimMoya** [comment]
I think the problem is in the IFC file, in the line:
- > #1101= IFCWALLSTANDARDCASE('0D727We9H4qRujuveGx02c',#12,'SW - 025',$,$,#9020,#9057,'0D1C21E0-A094-44D1-BE2D-E39A10EC00A6');
References to #9020 and #9057 are missing in the IFC file, so it can't create the wall

**Comment by agviegas** [comment]
![image](https://user-images.githubusercontent.com/56475338/165930224-3a7272c6-46c1-4bcb-9ea4-662f0c8180b6.png)

BIMvision doesn't open this either. The problem is indeed in the IFC!

**Comment by thmax** [comment]
That's true for one wall (screenshot from Trimble)
But others shoud be displayed right ?
![image](https://user-images.githubusercontent.com/52961165/165933347-2d35722c-ca06-46b6-8ac8-d0c708ab2b64.png)

**Comment by agviegas** [comment]
Hum, fair enough. We'll try to add a catch when there's that kind of error!

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $200. More information [here](https://bounties.ifcjs.io/).

**Comment by QuimMoya** [comment]
We added some improvements:
- Now it sends a warning when some express lines are missing
- It is able to read IFCINDEXEDPOLYCURVE when it has a curve indices list

![image](https://user-images.githubusercontent.com/12625508/168549976-d2a9a4f1-d294-40b7-b054-265bedba5ba3.png)

**Comment by tomerel22** [comment]
Can you send a link to your project? @QuimMoya
