### ISSUE TITLE
Issues with the curved geometry

### ISSUE THREAD

**Issue by ChidamSG** [tomvandig/web-ifc#145]
Version: 0.0.32
Curved geometry comes in as a full circular element. Looks like the Boolean operation was not working. 
![Curved Element](https://user-images.githubusercontent.com/99774943/154180613-9249ada1-cb40-4509-ba1d-63df4a4843eb.png)
https://drive.google.com/file/d/1CPY6LwPhOnqHTTdCBkBkCcCV0KWlWm7y/view?usp=sharing

Note: It works fine when I re-export the IFC file.

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $100. More information [here](https://bounties.ifcjs.io/).

**Comment by QuimMoya** [comment]
The origin of the problems seems to be here:
#414252= IFCTRIMMEDCURVE(#414251,(**#414240,IFCPARAMETERVALUE(90.)**),(#414244,IFCPARAMETERVALUE(0.)),.F.,.CARTESIAN.);

Trimming data is provided using points and values at the same time, Ifc.js was not prepared to digest that, now working on solving it.

**Comment by QuimMoya** [comment]
![image](https://user-images.githubusercontent.com/12625508/172798849-8354eefd-a76e-45e6-9939-46bbb266460e.png)
Seems to be solved, still have to verify
