### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by sabromeo** [tomvandig/web-ifc#15]
Had the following Error when Uploading this file:

https://drive.google.com/file/d/1bGCoofdHHJghlyD9fA1U20IvCxO5VJOk/view?usp=sharing

![](https://media.discordapp.net/attachments/799990228336115745/820854041361776730/unknown.png)

**Comment by tomvandig** [comment]
Hi.

Thank you for reporting this issue!

This file seems to work on https://tomvandig.github.io/web-ifc/examples/viewer/index.html

I see in the error message you were working with IFC.js. I think the IFC.js repository is simply out of date. We will update it when there is time.

![image](https://user-images.githubusercontent.com/49716596/111117413-c5b48580-8567-11eb-9a41-c39b5ff634a2.png)

**Comment by agviegas** [comment]
Hey, I have updated IFC.js. It should be using the last version now. Let us know if that works! 
![image](https://user-images.githubusercontent.com/56475338/111276726-eea44b80-8637-11eb-9b5f-d1974096b9f9.png)
