### ISSUE TITLE
ifcapi.OpenModel seems to ignore config with COORDINATE_TO_ORIGIN:true

### ISSUE THREAD

**Issue by MrGaribaldi** [tomvandig/web-ifc#151]
I'm trying to combine different IFC-models with other data sources, and so need to get the coordination matrix for the models. 
Using the online version here https://ifcjs.github.io/web-ifc-viewer/example/index and it will extract the matrix as expected. 
But I can't replicate the behavior with web-ifc, using b61bc028a4773f7bd6c23e73f6a5c2daf50cbe51

Changing line https://github.com/tomvandig/web-ifc/blob/b61bc028a4773f7bd6c23e73f6a5c2daf50cbe51/examples/nodejs/index.js#L16 to the following:
```
let modelID = ifcapi.OpenModel(ifcData, {COORDINATE_TO_ORIGIN:true, USE_FAST_BOOLS:true});
let coordMatrix = ifcapi.GetCoordinationMatrix(modelID);
```
I'd expect to get a matching coordination matrix as the web-viewer, but it stays identity.
Tested with the [Wellness Centre Sama](http://openifcmodel.cs.auckland.ac.nz/Model/Details/379) model from 
http://openifcmodel.cs.auckland.ac.nz/

**Comment by agviegas** [comment]
Hi @MrGaribaldi ! If I understood you correctly, you say that it works in web-ifc-viewer but not in web-ifc, right? 

As you might know, this library has 3 layers. From outside to inside: web-ifc-viewer, web-ifc-three and web-ifc. You should be able to reproduce it if you see what we did in [web-ifc-viewer](https://github.com/IFCjs/web-ifc-viewer/blob/54a6c1a34e106954b958925f9d0438daeb227545/viewer/src/components/ifc/ifc-manager.ts#L67) and [web-ifc-three](https://github.com/IFCjs/web-ifc-three/blob/29d750deeffa2e6e46cd9c6b83086d676497e68f/web-ifc-three/src/IFC/components/IFCParser.ts#L90). 

This is how we are implementing it. If you can't make it on your end, let us know and we'll happily guide you. Cheers!
