### ISSUE TITLE
Unsupported curve type

### ISSUE THREAD

**Issue by agviegas** [tomvandig/web-ifc#157]
The model is [here](https://drive.google.com/file/d/1a1lW9nxqBIjaduMnBvtn3H756E5Z5Rlk/view?usp=sharing).

**Comment by QuimMoya** [comment]
The IFC file is corrupt:

`#1077429= IFCTRIMMEDCURVE(#1077426,(IFCPARAMETERVALUE(0.),#1077384), IFCPARAMETERVALUE(179.03041),#1077388),.T.,.CARTESIAN.);`

Here there is a reference to a curve called #1077426 but the line #1077426 does not exist
