### ISSUE TITLE
Some meshes are missing

### ISSUE THREAD

**Issue by Undianer** [tomvandig/web-ifc#159]
![web-ifc_vs_ifcopenshell](https://user-images.githubusercontent.com/10446556/166646590-ba041c86-80e5-4cdb-ba47-41bf4db3d5e7.png)
Same problem here. On the left you see the loaded ifc from your demo viewer. On the right you see the ifc loaded by blenderbim which is based on ifcopenshell.
[Link to file](https://www.transfernow.net/dl/20220504rBAKGY6t) (Link is available for 7 days)
I hope there is a solution for that. 
Thanks in advance!

_Originally posted by @Undianer in https://github.com/tomvandig/web-ifc/issues/156#issuecomment-1117057952_

**Comment by agviegas** [comment]
Link [here](https://drive.google.com/drive/folders/1kf-cgH8bECbh9XS_mZXtTeilyPOlcKKD?usp=sharing) only for maintainers.

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $200. More information [here](https://bounties.ifcjs.io/).

**Comment by QuimMoya** [comment]
This issue is part of advanced breps, like #125 and #156.

**Comment by agviegas** [comment]
@QuimMoya we'll merge all of this in a single bounty!

**Comment by QuimMoya** [comment]
Yes, we have partially solved this issue, but this is related to AdvancedBreps so it is being done along many other issues all at the same time.
![image](https://user-images.githubusercontent.com/12625508/171371335-02d21cfc-1757-4682-9220-d3702aca042b.png)

**Comment by agviegas** [comment]
@vulevukusej yeah, it will take a little bit more time because it's complex. But it's in progress. 🙂

**Comment by Undianer** [comment]
Thank you very much! You guys are the best!
