### ISSUE TITLE
Support Concurrent load IFC files with web worker

### ISSUE THREAD

**Issue by wujiiu** [tomvandig/web-ifc#174]
Batch loading load files got same modelID and not all of the files can be displayed in the scene 

<img width="913" alt="image" src="https://user-images.githubusercontent.com/31948326/171625233-e65d6afe-420a-41a3-8809-5cab9edd3f1f.png">

**Comment by agviegas** [comment]
Hey! The data of web-ifc is stored inside its instance. This means that if you want to be able to load multiple models with multiple instances of web-ifc, you will need to keep each instance alive and ask the data of that model to the instance with which it was loaded. You could perhaps add a reference to that instance in the mesh? Cheers!
