### ISSUE TITLE
windows and doors not rendering properly

### ISSUE THREAD

**Issue by craigliesinger** [tomvandig/web-ifc#19]
Using web-ifc in Angular app - loading IFC file from Firebase.  All seems to go well, except windows and doors from model not rendering properly:
![Screen Shot 2021-03-27 at 9 02 48 PM](https://user-images.githubusercontent.com/10994930/112746279-15567080-8fae-11eb-8ae5-513f8895ba5f.png)

Example of screenshot from same model in other application:
![Screen Shot 2021-03-27 at 9 02 41 PM](https://user-images.githubusercontent.com/10994930/112746286-1edfd880-8fae-11eb-9365-ae851d751f48.png)

I can't see anything clearly identifying the problem in the console:
![Screen Shot 2021-03-28 at 9 57 11 AM](https://user-images.githubusercontent.com/10994930/112746291-22735f80-8fae-11eb-9649-ca486f435612.png)

Trying to show some property details from the IFC file (but I'm totally new to IFC, so not sure what information is really valuable here :) )
![Screen Shot 2021-03-28 at 10 10 45 AM](https://user-images.githubusercontent.com/10994930/112746293-27d0aa00-8fae-11eb-9dba-a8c9639f69d7.png)

**Comment by craigliesinger** [comment]
Trying to troubleshoot this a bit more (without the C++ / WASM skills to try fix on my own)... I notice with latest release with object highlighting & properties that the window geometries are being parsed as ifcWall (Wand-025):
![Screen Shot 2021-06-01 at 2 20 20 PM](https://user-images.githubusercontent.com/10994930/120344644-1089a200-c2fa-11eb-9b89-108424d19866.png)

Exploring the IFC I see in ArchiCADProperties that there is a property 'Überobjekt-ID' with value 'Wand-025' (Wall 25).  
![Screen Shot 2021-06-01 at 2 17 28 PM](https://user-images.githubusercontent.com/10994930/120344290-bf79ae00-c2f9-11eb-87e5-1fa4a878c436.png)

So seems somehow the parser is passing this 'upper object' or somehow getting crossed?  Or perhaps the IFC is somehow prepared incorrectly (I'm not the author of the IFC file)... but It loads properly in other viewers so I assume its fine.

Maybe I'll find some time to try and get brave enough to jump into the C++ but for now I thought this additional info may be of some little help

**Comment by tomvandig** [comment]
Hi,

This is an interesting issue. There could be a couple things going wrong, but its hard to investigate without the model.
You can contact me on discord and transfer it privately, or attach it here. 

Without the model, I can only guess.

**Comment by craigliesinger** [comment]
Sure.  Thanks Tom.  You should be able to download file here: https://firebasestorage.googleapis.com/v0/b/ziegelwerkstadt.appspot.com/o/houses%2Fhouse2%2FH01_Flachdach_Index01.ifc?alt=media&token=c3f08ffd-b814-4ab8-a486-d671046724b6

**Comment by tomvandig** [comment]
![image](https://user-images.githubusercontent.com/49716596/122283377-c2c18c00-ceec-11eb-8980-cbc18690bdfe.png)

Hi, this model will be fixed in 0.0.20

**Comment by craigliesinger** [comment]
I think there may have been an issue in the solution fix being pushed out with .20?  I've tried your example app in web-ifc repo and a Svelte example I made that also uses web-ifc 0.20.  I still get original result:
![Screen Shot 2021-07-13 at 1 52 09 PM](https://user-images.githubusercontent.com/10994930/125447251-2ec95004-f9bf-404b-a2b5-d992550f61ab.png)

**Comment by tomvandig** [comment]
Indeed my fix was incorrect, should be good in version 21. Let me know if the problem remains!
