### ISSUE TITLE
Does this library contain the full IFC object model?

### ISSUE THREAD

**Issue by ikeough** [tomvandig/web-ifc#20]
I've been following the development of @agviegas' [web IFC viewer](https://github.com/agviegas/web-ifc-viewer), and was wondering whether it supported the entire IFC object model, or just the geometric representations. I was linked through from that repo to here and took a poke around and couldn't find an implementation of the object model. Is that something that someone is currently working on? 

I previously built a project called [IFC-gen](https://github.com/hypar-io/IFC-gen) which has a full IFC parser and code generator. At Hypar, we will soon need the ability to load full IFC models in the browser (not just the geometry), and I was going to use IFC-gen to generate an IFC4 Typescript lib. I'm wondering whether it would be a useful complement to the work that you and @agviegas are doing.

**Comment by ikeough** [comment]
Seems like the object model is described in https://github.com/tomvandig/web-ifc/blob/main/src/schema/ifc4-elements.json, and this is somehow referenced by the wasm-compiled C++. I believe I've answered my own question :)

**Comment by tomvandig** [comment]
Hi Ian!

This is something I'm currently working on in the export branch. It's WIP right now, but I intend to support the entire 4.2 schema as javascript objects. Specifics on how to use it are pending, but essentially I want to make read/write on every IFC type as easy as possible.

The file you linked was used originally, but will be phased out soon.

I will close [this issue](https://github.com/tomvandig/web-ifc/issues/4) once I integrate it.

Cheers,
Tom

**Comment by tomvandig** [comment]
Hi Mathias,

Thank you for the kind words.

I am in the process of phasing out the ifc4-elements.json in favor of a typescript binding generated directly from the buildingsmart .exp definition file. You can find the typescript schema file [here](https://raw.githubusercontent.com/tomvandig/web-ifc/main/src/ifc2x4_helper.ts) (its quite large).

I don't have a strict requirement for an intermediate format but only on the generated code, and although parsing the .exp is a little annoying, I don't think it is complicated enough to warrant including an external binary, or even worse, include the rust toolchain into the project.

If you were to publish your AST as a JSON this might be helpful though, as you may have done a much better job at parsing the schema than my quick attempt [here](https://github.com/tomvandig/web-ifc/blob/main/src/schema/gen_functional_types.ts) which I have only run on ifc4.2 and also does not parse rules and functions either. But then the source code must be public so it can be maintained over time.

If you could open an issue with an example json schema, we can discuss the possibilities.
