### ISSUE TITLE
LGTM warnings

### ISSUE THREAD

**Issue by mrdoob** [tomvandig/web-ifc#24]
We use [lgtm](https://lgtm.com/) in three.js and we've noticed `web-ifc-api.js` has a few warnings:
https://lgtm.com/projects/g/mrdoob/three.js/snapshot/0d37b6de513cc0e33ff7184594bce9b821509152/files/examples/jsm/loaders/ifc/web-ifc-api.js?sort=name&dir=ASC&mode=heatmap

**Comment by agviegas** [comment]
That code is automatically generated by emscripten. It looks like they're just unused variables and redundant boolean evaluations.  We'll clean it up programatically to get rid of those warnings!

**Comment by agviegas** [comment]
Hey, I've tried to rectify the issues but it doesn't work. Apparently, even though there are unused variables and dubious boolean expressions, WASM needs this code the way Emscripten generates it. I'm not happy with this, but I guess that fiddling with this auto-generated code is not an option. 

![image](https://user-images.githubusercontent.com/56475338/115933757-d96cd900-a48f-11eb-8c5e-42b4d01d97ec.png)

I might be wrong, but I assume that the reason for using a code reviewer is to ensure the quality and maintainability of the repository, avoiding flaws and smells; in the case of this code, it is an output automatically generated by Emscripten (i.e. there is no maintenance and no chance of it being wrong), so maybe it shouldn't be evaluated as if it were code written by us. 

I've checked the lgtm documentation and it looks like there are [mechanisms to ignore specific files](https://lgtm.com/help/lgtm/alert-suppression). Do you think this solution would work for Three for this specific file? Sorry for the inconvenience!

**Comment by mrdoob** [comment]
I think using LGTM's alert suppression comments should work 👍
