### ISSUE TITLE
Geometry view issue

### ISSUE THREAD

**Issue by richardgush** [tomvandig/web-ifc#29]
Hi Tom, I converted one of the Revit example files to ifc and there is a small geometry issue in the ifc.js viewer.

[1621203160635-rstbasicsampleproject.ifc.zip](https://github.com/tomvandig/web-ifc/files/6496795/1621203160635-rstbasicsampleproject.ifc.zip)

**Comment by vegarringdal** [comment]
tested if its still buggy with 0.19
Got this

![image](https://user-images.githubusercontent.com/2901416/121066231-f2281880-c7c9-11eb-8668-f77c8603bcbe.png)

**Comment by tomvandig** [comment]
Will be fixed in v0.0.20

https://tomvandig.github.io/web-ifc/examples/viewer/index.html
