### ISSUE TITLE
cannot find module ./ifc2x4 and ./ifc2x4_helper

### ISSUE THREAD

**Issue by craigliesinger** [tomvandig/web-ifc#30]
I'm trying to upgrade from 0.0.17 to 0.0.18 and I get the following error when trying to serve:

Error: node_modules/web-ifc/web-ifc-api.d.ts:1:15 - error TS2307: Cannot find module './ifc2x4' or its corresponding type declarations.

1 export * from "./ifc2x4";
                ~~~~~~~~~~
Error: node_modules/web-ifc/web-ifc-api.d.ts:2:15 - error TS2307: Cannot find module './ifc2x4_helper' or its corresponding type declarations.

2 export * from "./ifc2x4_helper";

Any help would be greatly appriciated!

**Comment by craigliesinger** [comment]
The issue may still be valid, but better approach for me was to simply use the the Threejs Loader implementation and use all api calls via it.

**Comment by agviegas** [comment]
Indeed, generally it's better to use either the Three.js IFC Loader or [web-ifc-viewer](https://github.com/agviegas/web-ifc-viewer)!
