### ISSUE TITLE
Geometries are not displayed properly

### ISSUE THREAD

**Issue by htlcnn** [tomvandig/web-ifc#31]
ping @agviegas 
I have two models attached.

[model1.zip](https://github.com/tomvandig/web-ifc/files/6508542/model1.zip)
[model2.zip](https://github.com/tomvandig/web-ifc/files/6508545/model2.zip)

I opened them with IFC.js. Some geometries were not displayed, or not displayed properly. I use BlenderBIM addon to compare visually. Here are some images:

## Model 1

**IFC.js**
![image](https://user-images.githubusercontent.com/931924/118809781-42037600-b8d5-11eb-8f1d-80eb0d15a129.png)

**BlenderBIM**
![image](https://user-images.githubusercontent.com/931924/118810005-8b53c580-b8d5-11eb-88de-7496e0a5cfe0.png)

## Model 2

**IFC.js**
![image](https://user-images.githubusercontent.com/931924/118810111-b0483880-b8d5-11eb-9adc-9be0faaeb0b0.png)

**BlenderBIM**
![image](https://user-images.githubusercontent.com/931924/118810280-e2599a80-b8d5-11eb-83b0-33b7790e4cab.png)

If you knows how to inspect all objects parsed by IFC.js, please let me know so I could compare the objects in details (such as comparing their volume)
Thanks!

**Comment by agviegas** [comment]
Hey, in the console there must be some warnings about the geometries that we haven't implemented yet (pressing F12). We'll implement them asap!

**Comment by htlcnn** [comment]
@agviegas Here are console logs:

For model1: many `Unexpected curve type`
[model1.log](https://github.com/tomvandig/web-ifc/files/6520265/model1.log)

For model2: no exception so I assume all geometries in this model are implemented, but some still look weird
[model2.log](https://github.com/tomvandig/web-ifc/files/6520266/model2.log)

**Comment by tomvandig** [comment]
[Model1 is fixed](https://tomvandig.github.io/web-ifc/examples/viewer/index.html), model 2 pending investigation

![image](https://user-images.githubusercontent.com/49716596/121245943-e0657480-c8a0-11eb-8ff3-e05cf93db192.png)

**Comment by tomvandig** [comment]
Update for model 2, I had some problems in the curve code causing the straight lines. I've fixed some bugs there, and it looks correct. I still have a geometry issue left as you can see below, will update later. 

Also I was unable to load this model with the current bool lib, screenshot below is the old bool lib, so I am considering replacing that now.

![image](https://user-images.githubusercontent.com/49716596/122228178-e1f1f680-ceb7-11eb-8946-4c6b20512f2f.png)

**Comment by tomvandig** [comment]
These are now both rendering correctly.
