### ISSUE TITLE
how to import lib properly?

### ISSUE THREAD

**Issue by antoniohof** [tomvandig/web-ifc#32]
I can't find anything in the dist folder.
Just doing npm install doesn't work.
require and import doesn't work.

thanks

**Comment by harrycollin** [comment]
@antoniohof you should refer to the ['Building the library](https://github.com/tomvandig/web-ifc#building-the-library)' section of the readme. What are you trying to achieve?

**Comment by antoniohof** [comment]
Hi,
I did
npm install web-ifc

and then later
const WebIFC = require("web-ifc/web-ifc-api.js");

says it can't find 'web-ifc',
I checked node modules and it's there.

I will double check everything
thanks
