### ISSUE TITLE
IFC string escape is done by two single quotes

### ISSUE THREAD

**Issue by ottosson** [tomvandig/web-ifc#33]
Hi!

Just wanted to comment on this https://github.com/tomvandig/web-ifc/blob/f7da7d9b8010157e7f8e50eda6e0f1561310ca3c/src/wasm/include/parsing/tokenizer.h#L94

This is not an edge case. In [ISO 10303-21](https://en.wikipedia.org/wiki/ISO_10303-21) this is the way to escape a single quote. 

Here is an excerpt from the EXPRESS specification.

![image](https://user-images.githubusercontent.com/3355320/119313047-5ea40300-bc73-11eb-8f6a-9c8584385724.png)
![image](https://user-images.githubusercontent.com/3355320/119313128-78454a80-bc73-11eb-87c5-2ca9acb5be88.png)

Weird? Definitely!

**Comment by tomvandig** [comment]
Hi!

Thanks for the info! 

Indeed its weird, I'll update the comment!

**Comment by tomvandig** [comment]
Fixed in latest commit
