### ISSUE TITLE
Unexpected Style Type

### ISSUE THREAD

**Issue by messiosmarios** [tomvandig/web-ifc#34]
Hey guys, I've tried loading a project exported from Rhino, using VisualARQ tools to design and export in IFC2x3. I get these 'Unexpected Style Type' errors in the console. Thanks! Awesome work btw :)

Console Log
[1622037044905.log](https://github.com/tomvandig/web-ifc/files/6547196/1622037044905.log)

Screenshot
![image](https://user-images.githubusercontent.com/23511558/119672952-ac6f6580-be43-11eb-8f42-31480ee53cce.png)

IFC file
[HouseZ.zip](https://github.com/tomvandig/web-ifc/files/6547234/HouseZ.zip)

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $100. More information [here](https://bounties.ifcjs.io/).

**Comment by QuimMoya** [comment]
Solved
![image](https://user-images.githubusercontent.com/12625508/172831755-8b4d7daa-da62-46bc-8a39-8245965e365c.png)
