### ISSUE TITLE
Browser is freezing with some specific IFC file 

### ISSUE THREAD

**Issue by sinsunsan** [tomvandig/web-ifc#35]
http://openifcmodel.cs.auckland.ac.nz/Model/Details/331  it freeze the browser to parse the file. 

It is possible to set some limit to the resource used in the client computer ? If some operations are really intensive, a time-out maybe ?
Or other strategies that prevent from freezing the browser, I mean make it non-responsive

**Comment by tomvandig** [comment]
I can try to abort the boolean calculation if some #vertex-threshold is surpassed, will update this issue when its in.

**Comment by tomvandig** [comment]
In 0.0.20 you can try a different bool algo which performs better:

https://tomvandig.github.io/web-ifc/examples/viewer/index.html

**Comment by tomvandig** [comment]
From 0.0.23 you can use https://github.com/tomvandig/web-ifc/blob/410612d38a88cb645833dae1291dc1993b6969d5/src/web-ifc-api.ts#L28 to abort a boolean operator exceeding some vertex count, defaults to 10k
