### ISSUE TITLE
Retrieve IFC data by ExpressID

### ISSUE THREAD

**Issue by agviegas** [tomvandig/web-ifc#4]
Currently, the library is able to generate geometry based on an IFC. However, in almost all use cases it will be necessary to be able to access the data associated with each instance.

Probably the simplest way to do this would be to create an endpoint that has an ExpressID as input and returns a javascript object / dictionary with the retrieved properties. This presents two problems: how the user has access to the ID whose information they want to know, and where the data is stored where web-ifc is able to retrieve information from that ID.

Regarding the first problem, the most immediate is that every time a geometry is created, the API should return the ExpressID of the instance created. In this way, this ID could be associated to the geometry (e.g. each THREE Mesh would have an additional field with the ExpressID), so that when the user clicks on an object, a request is sent to the API with this data.

Storing this information in memory can be very penalising in medium and large projects. For this reason, we may want to use Emscripten's communication with IndexedDB, called [IDBFS](https://emscripten.org/docs/api_reference/Filesystem-API.html). This would allow us to make calls to this "small frontend database" and retrieve the information while keeping memory usage low.

**Comment by haroldiedema** [comment]
@agviegas Just an idea, but wouldn't it be easier to _only_ have an `expressId` exposed on the generated geometry, for example in Three's `userData` object?

Writing a parser to extract metadata from IFC files ourselves isn't such a big deal after all, and you'd let the user of this library decide for themselves how to implement this. This way you don't have to worry about memory management. Or perhaps use this as a starting point and worry about implementing the exposing of metadata later?

I personally wouldn't mind having two different libraries for this purpose. One for rendering, and another one for extracting metadata.

**Comment by agviegas** [comment]
@haroldiedema our guess is that having an endpoint that gets an ExpressID and returns a JS object with the data of that entity is easy enough for a first try. Then, the consumer of the library can use this endpoint recursively to get all the information they want. Let's see how it goes; if it gets to complex or in the future we find that it can't be scaled, moving it out to a separate repository is always an option.

**Comment by tomvandig** [comment]
First version of this was added in 1504db6709dc73059a0c1cc1aa345c707e01d571
Example can be seen in https://github.com/tomvandig/web-ifc/blob/d35afe73a960fac018c4b50d1ea509bf0460de00/examples/nodejs/index.js#L23

Some work still needs to happen to make it more user friendly, but the general idea is there. 
Will keep this issue open until it is more complete.

**Comment by tomvandig** [comment]
With the integration of the export branch, I consider this closed. Improvement suggestions to the current solution are of course welcome, please add new issues if needed.
