### ISSUE TITLE
Error loading model

### ISSUE THREAD

**Issue by agviegas** [tomvandig/web-ifc#40]
I'll send you the model privately. Thanks!
```
main.js:68813 RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (main.js:31757)
    at _abort (main.js:35480)
    at <anonymous>:wasm-function[48]:0x1189
    at <anonymous>:wasm-function[448]:0x2ecd6
    at <anonymous>:wasm-function[938]:0x53374
    at <anonymous>:wasm-function[939]:0x53396
    at Object.GetGeometry (eval at new_ (main.js:1), <anonymous>:9:10)
    at IfcAPI.GetGeometry (main.js:67378)
    at IFCParser.getBufferGeometry (main.js:68534)
    at IFCParser.savePlacedGeometryByMaterial (main.js:68527)
```

**Comment by tomvandig** [comment]
Looks like you're simply running out of memory. I will try to reduce the memory usage on the WASM side to solve this issue, but in the end there's a fixed limit to the WASM heap that cannot be exceeded.

**Comment by agviegas** [comment]
If there's a fixed limit, changes in web-ifc-three shouldn't have an effect on this, right? 🤔

**Comment by telegong** [comment]
> Looks like you're simply running out of memory. I will try to reduce the memory usage on the WASM side to solve this issue, but in the end there's a fixed limit to the WASM heap that cannot be exceeded.

I've loaded 220MB IFC file and can't load more files. AKA wasm32 memory limit 4GB. Chrome using 3.2GB in memory. I've heard wasm64 can exceed 1600TB in memory. Is wasm64 available with web-ifc?

**Comment by tomvandig** [comment]
This model is fixed in the latest deployment of https://tomvandig.github.io/web-ifc/examples/viewer/index.html

**Comment by vegarringdal** [comment]
@tomvandig nice 🥇
