### ISSUE TITLE
Support for IFCPRODUCTREPRESENTATION

### ISSUE THREAD

**Issue by ABaaS-dev** [tomvandig/web-ifc#41]
First, I'd like to thanks you for this wonderful project, it really helps getting up to speed with the IFC.

I setted up a little test env in which I'm able to view some IFC file but some of them are still not working.
In the console, I got the following kind of logs:
Unexpected mesh type: 2095639259 at 9999

After a quick analysis, the error seems to refer to line where I have IFCPRODUCTREPRESENTATION in the file.
I checked in the files that I'm able to display and non of them is using IFCPRODUCTREPRESENTATION.

For the record, I'm using the latest version of the wasm (0.19).
The non working ifc file is attached.

Thanks
[test2.zip](https://github.com/tomvandig/web-ifc/files/6622040/test2.zip)

**Comment by tomvandig** [comment]
This is a weird file, all the references point backwards :)

Anyway, thats allowed so no problem.

It's fixed, you can check out https://tomvandig.github.io/web-ifc/examples/viewer/index.html
Will be released in version 0.0.20

**Comment by ABaaS-dev** [comment]
Thanks  a lot for the quick answer and fix !

Any idea on when version 0.0.20 will be released ?

**Comment by tomvandig** [comment]
I'm working on some curve code for another issue that I have to fix. Maybe this evening, maybe not. It's a process.

:)

**Comment by tomvandig** [comment]
These kinds of missing elements are easy to find and correct, provided I have A model.

It doesn't have to be your exact model, if you can conjure up any model with that property (or point me to one available online) I can easily solve it for you. Also please open up an issue if you find such a model.

To keep things fun for me, I don't hunt for these models myself, sorry.
