### ISSUE TITLE
Walls starting above the ground

### ISSUE THREAD

**Issue by ABaaS-dev** [tomvandig/web-ifc#43]
I have an issue with a Revit IFC, the walls are not from the ground but a bit above:
![image](https://user-images.githubusercontent.com/85176686/121480955-ec9a2080-c9cb-11eb-904f-c2996e4725b1.png)

I tested with Solibri and everything is displayed correctly:
![image](https://user-images.githubusercontent.com/85176686/121481050-09365880-c9cc-11eb-9ece-b21960177e43.png)

The ifc file is attached :
[testnat1.zip](https://github.com/tomvandig/web-ifc/files/6629113/testnat1.zip)

Thanks

**Comment by tomvandig** [comment]
Update for 0.0.20

![image](https://user-images.githubusercontent.com/49716596/122819367-ac477600-d2da-11eb-8d7b-dbc8f78c9623.png)

Although some problems remain:

![image](https://user-images.githubusercontent.com/49716596/122819791-2bd54500-d2db-11eb-8e67-f0726d4ebabe.png)

**Comment by tomvandig** [comment]
I've looked at this file some more and it turns out one of the openings has inverted faces, which need to be fixed. I am not sure how complicated that will be, but I will let you know if I have progress.

**Comment by agviegas** [comment]
Solved by the amazing @tomvandig 🙂

![image](https://user-images.githubusercontent.com/56475338/168492652-f2fbfdad-220f-4615-87fc-868a56db4451.png)
