### ISSUE TITLE
Support for IFCCOMPOSITEPROFILEDEF

### ISSUE THREAD

**Issue by ABaaS-dev** [tomvandig/web-ifc#44]
I cannot not load a file containing the IFCCOMPOSITEPROFILEDEF tag.
I get the following log:
Unexpected profile type: 1485152156 at 686

Please find bellow the ifc file:
[test_IFCCOMPOSITEPROFILEDEF.zip](https://github.com/tomvandig/web-ifc/files/6629581/test_IFCCOMPOSITEPROFILEDEF.zip)

Thanks

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $100. More information [here](https://bounties.ifcjs.io/).

**Comment by QuimMoya** [comment]
Solved?
![image](https://user-images.githubusercontent.com/12625508/172832343-d27ca714-646a-4a24-8698-4725628e045f.png)
