### ISSUE TITLE
Different wasm file path in Chrome and Firefox

### ISSUE THREAD

**Issue by makinita** [tomvandig/web-ifc#45]
The integration of web-ifc-viewer in my project works fine in Firefox but not completely in Chrome.

Firefox loads the .wasm file from root: my-project.com/web-ifc.wasm
Chrome loads it prepending "**js/**": my-project.com/js/web-ifc.wasm

Even if I use _setWasmPath('my-dir')_ chrome still prepends "**js/**": 
my-project.com/js/my-dir/web-ifc.wasm (chrome)
my-project.com/my-dir/web-ifc.wasm (firefox)

Finally I could resolve it setting _setWasmPath('../')_, so all browsers loads wasm file from root

**Comment by makinita** [comment]
moved to web-ifc-viewer

**Comment by antoniohof** [comment]
Also happens to me. Cant set up a URI wasm path, it always prepends the current url.
