### ISSUE TITLE
Strange artifacts when loading some models

### ISSUE THREAD

**Issue by kovacsv** [tomvandig/web-ifc#46]
I've tried to load these models with the published viewer (https://tomvandig.github.io/web-ifc/examples/viewer/index.html):
- https://github.com/agviegas/test-ifc-files/blob/main/Revit/rst_basic_sample_project.ifc
- https://github.com/agviegas/test-ifc-files/blob/main/Structures/simple%20rebar.ifc

Both model contains some strange artifacts that are not there when opening it in another application.

![image](https://user-images.githubusercontent.com/2034315/121843981-8838d300-cce3-11eb-85d2-94e9f29503fe.png)
![image](https://user-images.githubusercontent.com/2034315/121844024-94bd2b80-cce3-11eb-9a42-d30cbb468069.png)

**Comment by tomvandig** [comment]
#1 fixed in https://tomvandig.github.io/web-ifc/examples/viewer/index.html
Will be in 0.0.20

**Comment by tomvandig** [comment]
#2 also fixed in https://tomvandig.github.io/web-ifc/examples/viewer/index.html
