### ISSUE TITLE
Include IfcSpace as a type of object whose geometry to generate when loading an IFC

### ISSUE THREAD

**Issue by agviegas** [tomvandig/web-ifc#49]
This is not urgent, but should be easy!

**Comment by tomvandig** [comment]
In 0.0.20 you can request your own geometries using GetFlatMesh.

**Comment by ABaaS-dev** [comment]
Hi,

I tried using GetFlatMesh with the expressID of an IfcSpace but not geometry is retrieved and I have the following log:
Unexpected mesh type: 3856911033 at 16132

I'm using the 0.0.20 version.

Am I missing something here ?

Thanks

**Comment by eng-luciano-julien** [comment]
I got the same problem.
