### ISSUE TITLE
Extra faces in extrusions with holes

### ISSUE THREAD

**Issue by agviegas** [tomvandig/web-ifc#5]
The current implementation of extrusions with holes looked correctly on simple meshes, but a look at a more complicated mesh demonstrates that there is a problem: there are extra faces in the direction of the extrusion.

![image](https://user-images.githubusercontent.com/56475338/110398203-ac956b80-8073-11eb-941c-cf41b2b8f276.png)

My guess is that this has something to do with the determination of the "vertical" faces of the extrusion: probably something like generating a vertical face foreach **n** and **n + 1** vertices. I'll take a look at it and see if I can make this work for extrusion with holes (probably overloading the function).

**Comment by haroldiedema** [comment]
I have a similar model here (https://iedema.me/haus.ifc) which shows similar artifacts. This model comes from a wikipedia source and is free to use / used as an example IFC file.

![image](https://user-images.githubusercontent.com/567518/110789949-bafca680-8270-11eb-8756-188d36dd47e1.png)

My guess is that earcut might be a culprit here.

**Comment by agviegas** [comment]
Hey @haroldiedema I think that your case is a different problem. What happens in my model is that the extrusion is generating extra faces in the direction normal to the extrusion profile. In your case, it looks like there was a huge problem with the CSG operations. Can you handle us that model to take a look? Also, bringing this to a separate issue would be great!

**Comment by haroldiedema** [comment]
Will do :+1:
