### ISSUE TITLE
Where is ifc2x4.h?

### ISSUE THREAD

**Issue by nathalie-raffray** [tomvandig/web-ifc#50]
I'm trying to load an IFC file in a simple cpp program.

However I noticed web-ifc-geometry.h and web-ifc.h include "ifc2x4.h".
Does this file exist somewhere?

**Comment by tomvandig** [comment]
This file was previously generated by a command in the package.json.

However, a recent PR from @kovacsv  has included this file, so you can now find it here:
https://github.com/tomvandig/web-ifc/blob/main/src/wasm/include/ifc2x4.h
