### ISSUE TITLE
Models issues - Unexpected mesh type: 1856042241

### ISSUE THREAD

**Issue by vegarringdal** [tomvandig/web-ifc#52]
@tomvandig Ill send IFC files in discord like last time :-)

Is it much work to add option on how detailed circles should be ?

**brset1.ifc**

in blender
![image](https://user-images.githubusercontent.com/2901416/122933552-07c34380-d36f-11eb-8535-6cd0b1439862.png)

web-ifc-v20
Unexpected mesh type: 1856042241
![image](https://user-images.githubusercontent.com/2901416/122933692-275a6c00-d36f-11eb-8979-9ac4fba85219.png)

---

**brset2.ifc**

In Blender
![image](https://user-images.githubusercontent.com/2901416/122933882-540e8380-d36f-11eb-95d4-3246da46b719.png)

web-ifc-v20
Unexpected mesh type: 1856042241 
![image](https://user-images.githubusercontent.com/2901416/122933803-422ce080-d36f-11eb-8774-dc922e0edeb4.png)

**brset3.ifc**

In blender
![image](https://user-images.githubusercontent.com/2901416/122934162-92a43e00-d36f-11eb-8b31-cd42f7e3234a.png)

web-ifc-v20
Unexpected mesh type: 1856042241
![image](https://user-images.githubusercontent.com/2901416/122934019-70aabb80-d36f-11eb-9435-03fc975ddc2a.png)

**Comment by tomvandig** [comment]
I think these are RevolvedAreaSolids, it's also a problem in #21 

I will take a look when I have time

**Comment by tomvandig** [comment]
RevolvedAreaSolids have a first implementation now, there's still problems with the tangents on the connections between the segments, which are easy to fix. Also #2 has a bug where the rotation is incorrect. I will update this ticket once it's complete.

**Comment by agviegas** [comment]
Hey @vegarringdal is this still happening? If so, could you please send me the models? Cheers!

**Comment by agviegas** [comment]
Hey, @vegarringdal if you decide to send us the models, feel free to reopen this.
