### ISSUE TITLE
String encoding - problem with special characters

### ISSUE THREAD

**Issue by eng-luciano-julien** [tomvandig/web-ifc#58]
Hi,
I have an issue displaying special characters (ç, é). I am using the encoding utf8 in the web page.
![image](https://user-images.githubusercontent.com/82835289/123685811-143b1680-d81d-11eb-9fb0-c3fb0605e3e5.png)

The string name came that way in json.
![image](https://user-images.githubusercontent.com/82835289/123685932-392f8980-d81d-11eb-8398-4c1e5eb15346.png)

**Comment by kovacsv** [comment]
Quick and dirty solution on the JavaScript side:
```js
function DecodeIFCString (ifcString)
{
    let ifcUnicodeRegEx = /\\X2\\(.*?)\\X0\\/uig;
    let escapedUnicode = ifcString.replace (ifcUnicodeRegEx, '\\u$1');
    return decodeURIComponent (JSON.parse ('"' + escapedUnicode + '"'));
}
```

**Comment by eng-luciano-julien** [comment]
Thank you @kovacsv! It solves the problem.

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $100. More information [here](https://bounties.ifcjs.io/).

**Comment by yakovlevkll** [comment]
Hello everyone,

Is it any possible way to use decoder from @deadman2000 with provided javascript API?

**Comment by agviegas** [comment]
Hi @yakovlevkll what do you mean? This was already merged.

**Comment by yakovlevkll** [comment]
Thank you for your reply @agviegas! I found the problem with the version of `web-ifc` used in `hello-world` repo (0.0.35 instead of 0.0.36 with the problem fixed)

**Comment by Tamu** [comment]
Hi everyone,
I have a new issue with the export of Revit 2022.1+ which integrates the ODA SDK exporter (ODA IFC SDK 22.8)

1. EXPRESS Data Manager : `\X2\00E9\X0\`
2. ODA IFC SDK  :   `\X\E9`

I confirm that with v1 the characters are ok, but not translated with v2.

I don't know for what obscure reason the Express Data was replaced by ODA !?
[update Revit 2022.3](https://help.autodesk.com/view/RVT/2022/ENU/?guid=GUID-19C4F8E4-7F92-402A-9133-04A252D09020)

**Comment by Tamu** [comment]
Thanks @agviegas for your answer !
I found an interesting link: [Revit-IFC](https://github.com/Autodesk/revit-ifc/issues/441)

**Comment by agviegas** [comment]
@Tamu awesome. If you find any problems with that, don't hesitate to create a new issue in this repo so that we can help you out. Cheers!
