### ISSUE TITLE
How to know the translation of the config COORDINATE_TO_ORIGIN: true

### ISSUE THREAD

**Issue by eng-luciano-julien** [tomvandig/web-ifc#59]
Hi,
I want to use the config COORDINATE_TO_ORIGIN: true. And I am adding some objects manually in the scene.
How to know the translation of the model the config did, in order to place correctly my objects.

Thanks in advance

**Comment by vegarringdal** [comment]
Its probably just easier to do do the translation your self/or @agviegas can add it as a option to the viewer :-)

So when starting to load files, you can get center of the first element/geometry, and reuse that on all geometry and files added after.

**Comment by tomvandig** [comment]
Please see https://github.com/tomvandig/web-ifc/blob/main/examples/usage/src/coordination.ts for an example

Available in version 0.0.22

**Comment by eng-luciano-julien** [comment]
Thank you!
