### ISSUE TITLE
Window Opening in Wall works with ifc 2x3 but not with ifc 4 (wall fills opening)

### ISSUE THREAD

**Issue by phili3000** [tomvandig/web-ifc#63]
Hey,
I have a wall with a window opening. When i export it with ifc 2x3 then it looks like expected. When i export it with ifc 4 then it gets inverted, so the wall fills only the window opening.

Thanks and cheers!
Philipp

ifc 2x3:
<img width="778" alt="Bildschirmfoto 2021-07-07 um 18 07 35" src="https://user-images.githubusercontent.com/31009513/124931605-ae137800-e002-11eb-8413-87c8953cce1f.png">

ifc 4:
<img width="730" alt="Bildschirmfoto 2021-07-07 um 18 06 01" src="https://user-images.githubusercontent.com/31009513/124931661-ba97d080-e002-11eb-919e-f6a7688f9e28.png">

[Wall_ifc2x3.ifc.zip](https://github.com/tomvandig/web-ifc/files/6784926/Wall_ifc2x3.ifc.zip)
[Wall_ifc4.ifc.zip](https://github.com/tomvandig/web-ifc/files/6784929/Wall_ifc4.ifc.zip)

**Comment by tomvandig** [comment]
Thanks for reporting this, I've seen more inverted geometry lately, I will try to solve it when I have time.

**Comment by tomvandig** [comment]
Fixed in 21.
