### ISSUE TITLE
Bad boolean operation

### ISSUE THREAD

**Issue by agviegas** [tomvandig/web-ifc#68]
Model: https://drive.google.com/drive/folders/1CbhqhjPG_T56K1dUz4dYfarViB9am_xK?usp=sharing

![image](https://user-images.githubusercontent.com/56475338/127014967-1f19238b-9300-4574-99b8-612fb98d7245.png)

**Comment by tomvandig** [comment]
This file seems to be fixed:
https://tomvandig.github.io/web-ifc/examples/viewer/index.html

![image](https://user-images.githubusercontent.com/49716596/135276252-01070d8d-8e04-4189-82a0-28ca55b636d2.png)
