### ISSUE TITLE
Problem when rendering IfcBuildingElementProxy which are rectangle extruded shapes

### ISSUE THREAD

**Issue by favreau84** [tomvandig/web-ifc#69]
## Context

In this construction project, one company (company A) is managing all the openings changes from one Revit digital mockup. Every time a change occurs, the company A shares one IFC files with all the up-to-date openings. Consulting companies, like structural engineering consultants, need to update the execution blueprints from this IFC. 

## Problem

When using the web-ifc-three lib to render the openings in 3D, the opening shapes do not appear to be regular rectangles. However, this is the case with the BIMcollab software.

<img width="414" alt="element" src="https://user-images.githubusercontent.com/18169247/127193693-96363e4a-f6de-4c99-b740-dd0609694150.png">

The openings are mainly extruded shapes.

<img width="1279" alt="openings" src="https://user-images.githubusercontent.com/18169247/127193785-2d61d6fc-2e66-48f5-9f69-464b83d07b56.png">

#### Problem in one dimension

Using the orthographic camera in the Y and X direction, it appears that the "weird" shapes pb is limited to the view from above. It is like the extrusion did not work correctly.

<img width="613" alt="orthographic" src="https://user-images.githubusercontent.com/18169247/127194819-72dd839e-1ef2-48ce-b597-c5261d5aaf02.png">

## Files

[openings.ifc.zip](https://github.com/tomvandig/web-ifc/files/6887335/openings.ifc.zip)

#### Note

The model is globally translated far away from the origin... To be sure to view it with Three.js, the camera should target the center of its bounding box.

**Comment by tomvandig** [comment]
Hi,

Could you try out your model here and report back?
https://tomvandig.github.io/web-ifc/examples/viewer/index.html

Feels like it looks OK there, which could mean that the far-away-ness of your model is not correctly taken into account on web-ifc-three.

If you can verify it works correctly above, I can suggest a solution for the web-ifc-three repo

**Comment by favreau84** [comment]
@tomvandig , the model is perfectly loaded from your viewer. It is amazing !! That would be great indeed to have the same result with web-ifc-three. Is there a quick win tuning Three.js rendering ?

<img width="697" alt="fine" src="https://user-images.githubusercontent.com/18169247/127207645-4fd9fc58-63fa-466f-93e0-8ea3ea68b13b.png">

**Comment by agviegas** [comment]
Hey, if you move the issue to web-ifc-three, I'll happy to fix it!

**Comment by favreau84** [comment]
@agviegas, ok great, I copied it here : https://github.com/IFCjs/web-ifc-three/issues/30
