### ISSUE TITLE
Loading IFC4 file with IFC.js provokes a RunTimeError 

### ISSUE THREAD

**Issue by KiWiGiW** [tomvandig/web-ifc#71]
Error:
![image](https://user-images.githubusercontent.com/30846915/127524684-90edeee4-3439-47a1-ae27-6fb7f365abfe.png)

IFC4 file below

**Comment by agviegas** [comment]
https://drive.google.com/file/d/1PUcGEcE0K4mxE9krEynu7WCDimlOHWtr/view?usp=sharing

**Comment by agviegas** [comment]
Hey @KiWiGiW is this still happening? If so, can you please resend the model? We no have resources to fix all the issues of this repository. Cheers!

**Comment by agviegas** [comment]
Hey, if you are willing to share the model, feel free to reopen this!
