### ISSUE TITLE
Missing colors on parts with cutouts

### ISSUE THREAD

**Issue by fedelaport** [tomvandig/web-ifc#73]
Hello!

Boolean results seems to be losing the style assignment. Take this panel as example. In a desktop viewer I get this colors:

![image](https://user-images.githubusercontent.com/20012908/129189715-85151fc5-7619-4239-ac29-f4e6e29608b8.png)

With ifcjs I get this colors right now:

![image](https://media.discordapp.net/attachments/800000126998675457/875335655406862336/unknown.png)

This is the IFC:

[AAA.zip](https://github.com/tomvandig/web-ifc/files/6975109/AAA.zip)

In the IFC, they style comes always applied to the main solid. When you have a normal piece the representation points to the styled item itself.

![image](https://user-images.githubusercontent.com/20012908/129190973-ae266dc4-3b4e-4810-a861-9cfe7153ee64.png)

But when you have a part with a cutout, the representation points to the boolean result, being the styled item not the boolean result but the original solid.

![image](https://user-images.githubusercontent.com/20012908/129190664-662023bc-4085-4c9c-be67-7289df54c410.png)

If I can help just let me know.

**Comment by fedelaport** [comment]
Hey @tomvandig, any news about this? 😅

**Comment by tomvandig** [comment]
Hi @fedelaport,

I will do my best to get around to each issue in time.

However, I am unable to say when it will be, as my time to work on this project is very limited unfortunately.

I appreciate your enthusiasm in the project and I hope I can do an update soon.

Cheers.

**Comment by tomvandig** [comment]
Fix is in the main branch, you can check it here:
https://tomvandig.github.io/web-ifc/examples/viewer/index.html

Pending packge deploy

**Comment by fedelaport** [comment]
I just tested it and it works perfectly fine. Thanks @tomvandig! Closing this then.
