### ISSUE TITLE
Error loading ifc. RuntimeError: abort(Assertion failed: false, at: ./src/wasm/include/web-ifc.h,618,GetSetArgument). Build with -s ASSERTIONS=1 for more info.

### ISSUE THREAD

**Issue by sbstnkll** [tomvandig/web-ifc#75]
I try to load a ifc file locally. All other IFC files are loading like a charm, except of this one "walls.ifc":

![image](https://user-images.githubusercontent.com/31189168/129555779-469a6793-1f0e-46b9-b48e-dbff3beccf26.png)

This is the ifc-file: https://www.file.io/download/Vp4U2zpUXvHv

side info that may help: the walls.ifc file is successfully loaded in the "hello world" example of the ifcjs documentation (https://ifcjs.github.io/info/docs/Hello%20world)
<img width="624" alt="Bildschirmfoto 2021-08-20 um 10 38 17" src="https://user-images.githubusercontent.com/31189168/130205803-2584f4b5-26e8-4d3e-a48a-9025aebb3e38.png">

Appreciate any help.

**Comment by antoniohof** [comment]
I'm also having this with the most recent version

**Comment by pb40development** [comment]
any news on this?

recently a lot of projects/hackathons use ifc.js and I wonder if they aren't having the same issue? What are we doing wrong here? Or is it a version thing?

**Comment by sbstnkll** [comment]
any news on this?

recently a lot of projects/hackathons use ifc.js and I wonder if they aren't having the same issue? What are we doing wrong here? Or is it a version thing?

**Comment by agviegas** [comment]
Sorry for the delay! I can´t access to the file in Icloud. Could you please send it another way? That error happens if the wasm file is not the same as the library you are using. To check wether the problems lies on your setup or in the library, you can try the [sample viewer](https://tomvandig.github.io/web-ifc/examples/viewer/index.html). Can you reproduce it there?

**Comment by sbstnkll** [comment]
Sry. The icloud link was out of date. I just updated the file link:

walls.ifc:
https://www.file.io/download/Vp4U2zpUXvHv

**Comment by agviegas** [comment]
![image](https://user-images.githubusercontent.com/56475338/140305052-1d30a173-3682-475a-9610-f550a5cae572.png)

**Comment by sbstnkll** [comment]
ah. sry. the end of the week is approaching ;):

https://file.io/tKOZVHywfSbW

**Comment by agviegas** [comment]
I can load it [here](https://tomvandig.github.io/web-ifc/examples/viewer/index.html), which is the last version (0.0.26). The most likely cause is that I haven't had the time to update web-ifc-three and web-ifc-viewer yet. This means that they use web-ifc@0.0.25, and if you updated web-ifc, you are using the wasm file of 0.0.26. Is this the case? I'll try to update both modules today.

**Comment by sbstnkll** [comment]
Ok. I need to look this up in my repo. I get back to you if this is the case. Thanks :)

**Comment by SteamWind** [comment]
@sbstnkll So, was it the case?
