### ISSUE TITLE
Some elements in the ifc model are not displayed, see ifc file attached.

### ISSUE THREAD

**Issue by simpleSketche** [tomvandig/web-ifc#79]
![image](https://user-images.githubusercontent.com/71196100/131255121-a8cb259f-62c8-4c40-9246-d73d4ca1267e.png)

ifc model link:
https://drive.google.com/file/d/1n3OsCkr-Z-7z7MWt7gvn9U_YTPGQ0d5i/view?usp=sharing

**Comment by agviegas** [comment]
Hey @simpleSketche we now have resources to solve all the issues of this repo. Can you please give us access to the file? We have requested it through the ifc.js.contact@gmail.com account. Cheers!

**Comment by agviegas** [comment]
Hey @simpleSketche if you are willing to share the file, feel free to reopen this again!
