### ISSUE TITLE
Additional prereqs for build

### ISSUE THREAD

**Issue by pablo-mayrgundter** [tomvandig/web-ifc#8]
1) Typescript needs to be installed
2) Need to install node type defs.  Got this error:

```
lib/web-ifc-api.ts:5:20 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

5 const WebIFCWasm = require("./web-ifc");
```

The suggested fix worked.

**Comment by tomvandig** [comment]
Hi,

Thanks for posting this issue!

The instructions were missing the `npm install` command, I've added this just now.
The package.json includes "typescript": "^4.1.5" as a dev-dependency, so this should be fine.

On my local machine I don't need the node type defs, and I don't appear to have it installed globally.

Could you try again on the latest commit?

Thanks!

**Comment by pablo-mayrgundter** [comment]
Looks good.  Yeah, I have a few npms around.. global, brew and most locally for your project from emsdk.
