### ISSUE TITLE
`IFC` import fails with error `Unexpected placement type`

### ISSUE THREAD

**Issue by hey24sheep** [tomvandig/web-ifc#83]
Try importing an `.ifc` file (download from [here](http://openifcmodel.cs.auckland.ac.nz/)) it fails.

Error 
```Log
Reading took 0 ms
web-ifc-viewer.js:205252 Opening model took 16 ms
67web-ifc-viewer.js:938 unexpected placement type
web-ifc-viewer.js:203725 Uncaught TypeError: Cannot read properties of undefined (reading 'index')
    at Function.mergeBufferGeometries (web-ifc-viewer.js:203725)
    at IfcThree.LoadAllGeometry (web-ifc-viewer.js:204197)
    at LoadModel (web-ifc-viewer.js:205253)
    at FileReader.reader.onload (web-ifc-viewer.js:205236)
```

Error Image
![Capture](https://user-images.githubusercontent.com/31468022/132990875-f26914f2-acbb-42e5-b4ab-69f49eb1251e.PNG)

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $100. More information [here](https://bounties.ifcjs.io/).

**Comment by QuimMoya** [comment]
I think the model is in IFC2.0, ifc.js does not support this IFC version

**Comment by QuimMoya** [comment]
The IFC link is broken

**Comment by hey24sheep** [comment]
@QuimMoya Hi, I am not fully aware of the versions and difference in between them. [Here is the same repository of those models](http://smartlab1.elis.ugent.be:8889/IFC-repo/http.openifcmodel.cs.auckland.ac.nz/). 

NOTE: Some of the models work and some don't.

Here are the ones which work
- 301110PART02_Wilfer_200302_20070209_IFC
- 0912109-01railing_brep_ac_1

Here are a few those don't work are : (You can download these to try)
- 13111003_IFCR2_Geo_Doors_1
- 23111013_IFCR2_Geo_Walls_2
- 05111002_IFCR2_Geo_Columns_1

**Comment by agviegas** [comment]
Hey @hey24sheep we only support IFC from IFC2x3. You can see the version opening the IFC with a text editor, it's somewhere at the top. If you have an IFC that you know it's IFC2x3 onwards and still doesn't load, feel free to open more issues for them. Cheers!

**Comment by hey24sheep** [comment]
@agviegas I see, can it be added to Readme or FAQs? I might have missed it if it's already there. Thanks for the help.

**Comment by agviegas** [comment]
Hey @hey24sheep sure! Create an issue [here](https://github.com/ifcjs/info) and I'll add it. Cheers 😊

**Comment by hey24sheep** [comment]
@agviegas done 👍🏼 thank you
