### ISSUE TITLE
Inner radius of IFCSWEPTDISKSOLID currently not supported

### ISSUE THREAD

**Issue by VLegatus** [tomvandig/web-ifc#88]
![image](https://user-images.githubusercontent.com/19193927/136212024-9b39ffdf-f0a6-4e59-9be4-e6405f30c85a.png)
Jiggy on Discord brought this up, but I'm also having the same issue.
It seems to involve any tubular structure, and turns them into septagonal prisms.

The Sample IFC that I used:
http://openifcmodel.cs.auckland.ac.nz/Model/Details/348

**Comment by VLegatus** [comment]
It also seems to parse the IFC file as something much bigger

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $100. More information [here](https://bounties.ifcjs.io/).
