### ISSUE TITLE
Show "unexpected token" message

### ISSUE THREAD

**Issue by akoshorvath11** [tomvandig/web-ifc#89]
Hi! 
I uploaded ProVI IFC out file and the threw "unexpected token" error.

![image](https://user-images.githubusercontent.com/58355308/136384465-dc757223-a490-4013-9eed-0d609f2fce98.png)

The ifc file:
[IFCOUT2_model.zip](https://github.com/xeokit/xeokit-bim-viewer/files/7302532/IFCOUT2_model.zip)
Thank you in advance for your answer!

**Comment by akoshorvath11** [comment]
Thank you for your help!  This IFC file was created by the ProVI design software.  I don’t know if comments are allowed in the IFC schema.  I will follow the #96.

**Comment by tomvandig** [comment]
Actually I was wrong, IFC allows comments, just never encountered them before :)

I will fix this in the new version.
