### ISSUE TITLE
IFCSweptDiskSolid geometry definition error

### ISSUE THREAD

**Issue by penuttw0** [tomvandig/web-ifc#90]
Hi Tom,
Upon loading geometry following the IFCSweptDiskSolid IFC2X3 standard, The geometry for a curved pipe is distorted and the thickness of the pipes are not defined.  Additionally, the definition of the circular geometry has been rationalised into a octagonal shape rather than maintain the circular geometry. 

![image](https://user-images.githubusercontent.com/48374651/136473466-b7989963-c62e-4785-9982-e71b9cdd4e76.png)
![image](https://user-images.githubusercontent.com/48374651/136473489-58e89d50-2ff3-42f4-95a1-e06d11f968fa.png)

With the original intended geometry looking like this.
![image](https://user-images.githubusercontent.com/48374651/136473509-8adf9576-cf9d-4ea9-ba0f-f874b54cd4e6.png)

Cheers
Bryan

**Comment by penuttw0** [comment]
Hi Tom,

See attached, i hope this helps.

**Comment by agviegas** [comment]
Hi @penuttw0, I'm closing this issue. If you provide us with IFC files, feel free to reopen this again. Cheers!
