### ISSUE TITLE
Possible floating point error

### ISSUE THREAD

**Issue by QuimMoya** [tomvandig/web-ifc#96]
I'm trying to open a road using WEB-IFC project, the model is not very large, but it is placed very far away.

When i open it, WEB-IFC centers the model but, for some reason, there are floating point errors in visualization.

![image](https://user-images.githubusercontent.com/12625508/139045635-e99237ea-8654-4ff5-a74d-58d035137732.png)

I have verified that the geometry sent to THREE viewer is correct. Not sure what is happening.

I will work on it, and post any progress.

**Comment by agviegas** [comment]
This was already merged in the library, so I'm closing this.
