### ISSUE TITLE
convert2xkt memory access out of bounds 

### ISSUE THREAD

**Issue by noblejrepo** [tomvandig/web-ifc#97]
Hi,

I'm trying to convert IFC with convert2xkt but some ifc have this issues. And I can't convert them.

Do you have an advance for me to find out where is the problem come from ?

comand on centos : #convert2xkt.js -l -s file.ifc -o file.xkt

OUTPUT :
Error: RuntimeError: memory access out of bounds
at :wasm-function[297]:0x1b016
at :wasm-function[474]:0x35fe0
at :wasm-function[114]:0x699d
at :wasm-function[474]:0x346c7
at :wasm-function[114]:0x699d
at :wasm-function[474]:0x34497
at :wasm-function[114]:0x699d
at :wasm-function[474]:0x3337b
at :wasm-function[114]:0x699d
at :wasm-function[988]:0x5f56c

This error (RuntimeError: memory access out of bounds) from this function "LoadAllGeometry(modelID) " but I watched deeply and I don't see why.  (code in web-ifc-api.cpp)

![web-ifc-api](https://user-images.githubusercontent.com/32675298/139061041-133ceb9c-0b3b-4173-996f-05dab53ee3bd.PNG)

Any tips for me ?

**Comment by noblejrepo** [comment]
Hi @tomvandig ,

I am sorry to disturb you again but when I am trying to buid "web-ifc.wasm" following the tutorial in this repos. But when I exectuted  "npm run build-release" I got this

![Capture](https://user-images.githubusercontent.com/32675298/140308002-fa33c019-4379-4f86-b543-4b2bcafbb280.PNG)

Any idea for me to resolve this ?

**Comment by tomvandig** [comment]
Yeah this is a work in progress, you need to run wasm-build-release-mt, apparently I did not include it in the build command yet

**Comment by noblejrepo** [comment]
The build works ! I replaced in "example/viewer/wasm/" the compiled files (web-ifc-mt.wasm,web-ifc.wasm) and I can see in my local viewer (localhost:5000/example/viewer/) the IFC.

I replaced the "web-ifc.wasm" in xeokit-convert/dist and launched the convertion but it was not worked. I got this 

![Capture](https://user-images.githubusercontent.com/32675298/140376275-cbe9f4e5-9746-4382-b1c2-7b5f125c9edc.PNG)

Any idea for me ?

**Comment by noblejrepo** [comment]
ok ! thank you for everything
