### ISSUE TITLE
Autility models with issues

### ISSUE THREAD

**Issue by agviegas** [tomvandig/web-ifc#99]
[Here](https://drive.google.com/drive/folders/1ClbRFtJVqxWVVZ4PabRXQ6UBDNdsKojY?usp=sharing) you have the files.

Result: 
![image](https://user-images.githubusercontent.com/56475338/139834858-969a64ab-e7fc-47ac-b967-8517bddf0291.png)

Result:
![image](https://user-images.githubusercontent.com/56475338/139834879-784b4760-4f0f-4a1c-8090-90c5f13ba050.png)

Expected:
![image](https://user-images.githubusercontent.com/56475338/139835083-8327f4e1-2c9e-46e8-a7d7-7a71cae73379.png)

Result:
![image](https://user-images.githubusercontent.com/56475338/139834754-9a2fc22b-e4e7-4555-8b76-26a94e13a9c7.png)

Expected:
![image](https://user-images.githubusercontent.com/56475338/139834766-2bbae7e7-518a-423d-b17d-df62ce7d8207.png)

**Comment by tomvandig** [comment]
![image](https://user-images.githubusercontent.com/49716596/144506646-7ce65462-9810-4cd3-ae42-384e1f6c136e.png)
![image](https://user-images.githubusercontent.com/49716596/144506784-6b37ee84-a79c-4994-af33-bdd687e7c301.png)
![image](https://user-images.githubusercontent.com/49716596/144506819-d7208520-64f9-4cf3-a73b-0eb41646eab4.png)

These look fixed now, in 0.0.30. Please reopen if another issue arises.
